openapi: 3.0.0

info:
  title: Supik Server
  description: Users and Computer management system
  version: 0.2.0-ALPHA

paths:
  /:
    get:
      summary: Docs
      responses:
        '200':
          description: Documentation for all endpoints

  /api:
    get:
      summary: Test
      responses:
        '200':
          description: Test home page
